### ISSUE TITLE
NuGet Error NU1108

### ISSUE THREAD

**Issue by jayonsoftware** [ttu/json-flatfile-datastore#27]
I am getting the A circular dependency was detected error if I use Net Core 2.2, if I use Net 4.5.X all is good.

**Comment by ttu** [comment]
Hi and thanks for the issue!

I don't get any error when using .NET Core 2.1.6. As 2.2 is still a preview, I think we should wait for the final release or the release candidate before taking any actions.

**Comment by ttu** [comment]
Tried with version 2.2.103 and didn't get any error, so this was likely caused by the preview version.
