### ISSUE TITLE
Guid persistence as Id

### ISSUE THREAD

**Issue by tgiachi** [ttu/json-flatfile-datastore#41]
Hi!
I have entity with Id (`keyProperty: nameof(Entity.Id));` as Guid but i receive this error

![image](https://user-images.githubusercontent.com/942730/65070695-66cf7980-d98d-11e9-97f9-3fd571584512.png)
 Can you help me?
Thanks!

**Comment by tlejmi** [comment]
assign value to id property using idValue.toSting()  and if you are using EntityFramework Identity customize identity to use int instead of guid.

**Comment by tgiachi** [comment]
ok thanks!

**Comment by ttu** [comment]
Apparently this was not a bug in JsonFlatFileDataStore? Will close this issue.

If there is something to be fixed please reopen this.
