### ISSUE TITLE
InsertItem gets stuck in .NET Core 3 WPF project

### ISSUE THREAD

**Issue by strohhut** [ttu/json-flatfile-datastore#42]
Hello!

**Steps to reproduce:**
Create a new WPF project with .NET Core 3 platform. Add JasonFlatFileDataStore (2.20) nuget package to it.

Add your example `Employee` class and add DataStore code to `MainWindow`:

```
public MainWindow()
{
    InitializeComponent();

    var store = new DataStore("data.json");
   
    var collection = store.GetCollection<Employee>();
   
    var employee = new Employee { Id = 1, Name = "John", Age = 46 };
   
    collection.InsertOne(employee); // Works

    store.InsertItem("counter", 1); // Stuck forever

    collection.InsertOne(new Employee { Name = "John", Age = 46 }); // Never reached
}

```

Run the WPF-project in debug mode.

**Additional info:**
`data.json` gets both the first employee and the counter inserted correctly, but the `InsertItem` code line gets stuck. `ReplaceItem` has the same problem. I tried above code (without `InitializeComponent`) in a .NET Core 3 console project and there were no problems.

**Comment by ttu** [comment]
Thanks for the issue!

Found the bug. `CommitAction` inside `InsertItem`, `ReplaceItem` and `DeleteItem` is always called as an async update. I will make a fix and release the patched version soon.

https://github.com/ttu/json-flatfile-datastore/blob/master/JsonFlatFileDataStore/DataStore.cs#L209
https://github.com/ttu/json-flatfile-datastore/blob/master/JsonFlatFileDataStore/DataStore.cs#L227
https://github.com/ttu/json-flatfile-datastore/blob/master/JsonFlatFileDataStore/DataStore.cs#L256

**Comment by ttu** [comment]
@strohhut patched version released https://www.nuget.org/packages/JsonFlatFileDataStore/2.2.1
