### ISSUE TITLE
Proofread README.md

### ISSUE THREAD

**Issue by ttu** [ttu/json-flatfile-datastore#5]
Fix all grammar, styling, spelling etc. errors from [README.md](https://github.com/ttu/json-flatfile-datastore/blob/master/README.md)

**Comment by robZeilinga** [comment]
Hi ttu, 
only confusion i picked up was the following :   - and it probably is me,...

> If JSON Flat File Data Store is used with e.g. ASP.NET, add the DataStore to the DI container as a singleton. This way DataStore's internal state is correct and application does not have to rely on the state on the file as read operation is pretty slow. Reload can be triggered if needed.

Can you provide an example - or a definition for the **DI container** ?
regards
RobZ

**Comment by ttu** [comment]
Hi,

Thanks for reading the documentation!

DI container is a short for Dependency Injection container.

You can read more from Microsoft’s docs:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1

So it seemed that besides that the text was mostly understandable and didn’t have noticeable typos?

**Comment by ttu** [comment]
@richardversluis thanks!

**Comment by ttu** [comment]
There has been already many people participating in the proofreading, so it is time to close this issue.

Thanks for all for help!
