### ISSUE TITLE
Using DI with a console app should I inject as singelton or transient?

### ISSUE THREAD

**Issue by VictorioBerra** [ttu/json-flatfile-datastore#51]
I am wondering how I should treat the lifetime of my DataStore. If it matters, im using a console app that runs and quits. Its very linear.

- If I do transient, I may have two different instances of it at once. Would that cause issues?
- If I do singleton, I suppose its possible to ask the same instance of DataStore to write to my file at once too.

Just trying to think through this, thanks!

```csharp
.AddSingleton<IDataStore>(serviceProvider =>
{
    var connectionString = serviceProvider.GetRequiredService<ConnectionStringsOptions>();
    return new DataStore(connectionString.DefaultDatabase, false);
})
```

VS

```csharp
.AddTransient<IDataStore>(serviceProvider =>
{
    var connectionString = serviceProvider.GetRequiredService<ConnectionStringsOptions>();
    return new DataStore(connectionString.DefaultDatabase, false);
})
```

**Comment by ttu** [comment]
Hi! 

It is recommended to add a collection to DI container as a singleton. This way DataStore's internal state is always valid.
https://github.com/ttu/json-flatfile-datastore#datastore-and-collection-lifecycle

Example from ASP.NET: https://github.com/ttu/dotnet-fake-json-server/blob/master/FakeServer/Startup.cs#L54

If you have more questions, don't hesitate to ask!

**Comment by VictorioBerra** [comment]
Thank you!
