### ISSUE TITLE
Update function not working

### ISSUE THREAD

**Issue by EricBellamy** [ttu/json-flatfile-datastore#54]
Given a "data.json" file with:
```
"worlds": [
    {
        "id": 0,
        "position": [
            3.6640577,
            5.5219193,
            3.4788187
          ],
         "cameraRotationX": -0.66699946,
         "cameraRotationY": -0.003000007
    }
]
```

Running the following update code:
```
var collection = gameStore.GetCollection("worlds");
await collection.UpdateOneAsync(e => e.id == 0, new { position = new float[] { 10, 10, 10} } );
```

The database does not save the update and will remain the same as the above mentioned example. This code was pulled directly from the docs. Is there something I missed? I tried out any other update function I could find in the docs as well with the same results.

Current solution is to delete and re-insert the entry.

**Comment by EricBellamy** [comment]
Given a "data.json" file with:
`
"worlds": [
{
      "id": 0,
      "position": [
        3.6640577,
        5.5219193,
        3.4788187
      ],
      "cameraRotationX": -0.66699946,
      "cameraRotationY": -0.003000007
    }
]
`

Running the following update code:
`
var collection = gameStore.GetCollection("worlds");
await collection.UpdateOneAsync(e => e.id == 0, new { position = new float[] { playerPos.X, playerPos.Y, playerPos.Z } } );
`

The database does not save the update. This code was pulled directly from the docs. Is there something I missed?

Current solution is to delete and re-insert the entry.

**Comment by ttu** [comment]
Thanks for the issue. 

Update function didn't check correctly the type of the item to be updated. Made a fix for it. I will test it more and if everything works, I will release a new version.

**Comment by EricBellamy** [comment]
Unbelievable response time, thank you!! I thought I had to have just been messing something up on my end. I really appreciate the fix!

**Comment by ttu** [comment]
No problem. Thanks for the good example data and code. Fixing bugs is so much easier when I can easily reproduce the bug 😄 

I will fix one other bug I found with typed arrays and then I will release a new version. Pretty likely during the weekend.

**Comment by ttu** [comment]
@EricBellamy New version is now released https://www.nuget.org/packages/JsonFlatFileDataStore/2.2.3

Have a nice summer!

**Comment by EricBellamy** [comment]
Thank you so much! I saw the repo update but missed this notification. I hope you have a good summer as well and stay safe! :smile:
