### ISSUE TITLE
Synchronizing Async Methods

### ISSUE THREAD

**Issue by pvoelker** [ttu/json-flatfile-datastore#67]
Synchronizing an async method (via a 'Result' or 'Wait()') seems to cause the entire app to lockup.  This is in a .NET 6 WPF application.

 I know this seems odd, but I'm slowly integrating async/await into my application.  For the moment I have to synchronize the async calls in my ICommands from the UI.

```
            using (var ds = new DataStore(_fileName, true, nameof(QuestionSet.PrimaryKey)))
            {
                var coll = ds.GetCollection<QuestionSet>();
                var success = coll.InsertOneAsync(value).Result;   **Application locks up here**
                if (success == false)
                {
                    throw new OperationFailedException("Add failed");
                }
            }
```

**Comment by ttu** [comment]
Hi!

Using Result should be avoided when using async methods. Especially in UI applications, this can cause deadlocks pretty easily.  Use `await`instead and if you can't use `await`, then it is better to use sync-methods. 

```cs
var success = await coll.InsertOneAsync(value);
if (success == false)
{
    throw new OperationFailedException("Add failed");
}
```

Haven't done UI app programming in C# in a while, so I don't know if there are some new helper methods for calling async code from sync-method that will prevent deadlocks.

This article seems to have good explanations and examples 
https://medium.com/rubrikkgroup/understanding-async-avoiding-deadlocks-e41f8f2c6f5d

If you have any other questions don't hesitate to ask and hope you find help from these :)

**Comment by pvoelker** [comment]
I found something to get me by this.  There is an internal class that you can find code for on the Internet called 'AsyncHelper'.  It seems to get me past the issue.   Like I said what I'm doing is strange, but taking my async conversion of my app in phases.  I'm working through some issues with AsyncRelayCommand in WPF.  So I'm sticking with the synchronous RelayCommands for now...  Thank you for the help
