### ISSUE TITLE
No Iterator over Collections?

### ISSUE THREAD

**Issue by gjvanvuuren** [ttu/json-flatfile-datastore#70]
This is a very neat little library, thanks. 

Now I've implemented my code, tested it, and realized to my dismay, that there's no iterator over the collections. Or is there a trick that I'm missing?

I'm just looking for something like ``db.GetCollections()``. Would it be possible to provide this? I imagine it can't be too difficult to implement.

**Comment by ttu** [comment]
Thanks for the feature request!

There is an interator over the collection names
https://github.com/ttu/json-flatfile-datastore/blob/2f5fd851781157f030c5b204cf8715d2ec3bb4a8/JsonFlatFileDataStore/IDataStore.cs#L37

Apparently there is no mention of that in the documentation, as it is not widely used. I will update the documentation later.

Is that functionality enough for your use case?

**Comment by gjvanvuuren** [comment]
Thanks for the feedback. This will do for me.
