### ISSUE TITLE
Support filesystem abstraction

### ISSUE THREAD

**Issue by ykarpeev** [ttu/json-flatfile-datastore#90]
I had a need to test this with a mocked filesystem. Used [ System.io.Abstraction.](https://github.com/TestableIO/System.IO.Abstractions) for this purpose.

Here are the changes in case it is helpful.

https://github.com/ykarpeev/json-flatfile-datastore/commit/83d4bc8094d55ba695d488ff955808e11871ef47

**Comment by ttu** [comment]
Thanks! This is very good. I have never used `System.IO.Abstractions` before. I was at one point thinking about adding a mock for `FileAccess`, but this is way better 👍
