### ISSUE TITLE
Replace Newtonsoft.Json with System.Text.Json

### ISSUE THREAD

**Issue by PSanilP** [ttu/json-flatfile-datastore#91]
Any plans to move the library to native system.text.Json from Newtonsoft? 
It is an unnecessary dependency and going forward likely to be deprecated

**Comment by ttu** [comment]
Hi! Currently there are no active plans to move away from Newtonsoft. We tried it some years ago, but there was some issues. Unfortunately we do not have any notes about issues we encountered.

We can definitely try this again 👍

**Comment by SpicyBagpipes** [comment]
> Hi! Currently there are no active plans to move away from Newtonsoft. We tried it some years ago, but there was some issues. Unfortunately we do not have any notes about issues we encountered.
> 
> We can definitely try this again 👍

Newtonsoft has problems with AOT compilation which seems like it will not be resolved:
https://github.com/JamesNK/Newtonsoft.Json/issues/2732

**Comment by ttu** [comment]
Short update: Unfortunately, I haven't had much time to work on this. The functionality still requires some fixes and plenty of testing. Once everything seems to work, the plan is to release the v3 beta version.

**Comment by ttu** [comment]
Hi, I’ll be replacing this issue with issue: https://github.com/ttu/json-flatfile-datastore/issues/101 

Additional details, progress tracking, and updates will be provided there.
