### ISSUE TITLE
Update is not updating the json File

### ISSUE THREAD

**Issue by jayonsoftware** [ttu/json-flatfile-datastore#92]
void Main()
{
	var phone1 = new Phone { Id=1, Name = "CELL", Number = "123" };
	var phone2 = new Phone { Id=2, Name = "LAND", Number = "456" };

	var customerOne = new Customer
	{
		Id=1,
		Name = "Jay",
		Phones = new List<Phone> { phone1, phone2 },
	};

	var customerTwo = new Customer
	{
		Id = 2,
		Name = "Jay",
		Phones = new List<Phone> { phone1, phone2 },
	};

	var store = new DataStore("c:\\dev\\data.json");
	var collection = store.GetCollection<Customer>();
	var done = collection.DeleteMany(x=>x.Name != "");

	collection.InsertOneAsync(customerOne);
	collection.InsertOneAsync(customerTwo);
	
	var results = collection.AsQueryable();
	results.Dump();
	
	foreach(var cus in results) {
		cus.Phones.RemoveAll(x=>x is not null);
// Does not update the json file
		var updateTask = collection.UpdateOneAsync(cus.Id, cus);
		updateTask.Wait();
	}
	
	results = collection.AsQueryable();
	results.Dump();
}

On the above code, the UpdateOneAzync updates the in-memory data but not the actual file.

Also what is the best way to drop the whole table? I am doing 

`	var done = collection.DeleteMany(x=>x.Name != "");`

and it works, but that's ugly

Thanks 

Jay

**Comment by ttu** [comment]
Thanks for the issue! I will create a test and confirm the problem.

Unfortunately there is not functionality for dropping the whole table. I can check if I can come up with some solution for it.

**Comment by jayonsoftware** [comment]
So I still cant seem to figure out how to update the JSON file once the changes are done.  Also noticed that the child objects the Id is always 0;
```

void Main()
{
	var customerOne = new Customer
	{
		Name = "Jay1",
		Phones = new List<Phone> { new Phone { Name = "CELL", Number = "123" }, new Phone { Name = "LAND", Number = "456" } },
	};

	var customerTwo = new Customer
	{
		Name = "Jay2",
		Phones = new List<Phone> { new Phone { Name = "CELL", Number = "123" }, new Phone { Name = "LAND", Number = "456" } },
	};

	var store = new DataStore("c:\\dev\\data.json");
	var collection = store.GetCollection<Customer>();
	var done = collection.DeleteMany(x=>x.Name != "");

	collection.InsertOneAsync(customerOne);
	collection.InsertOneAsync(customerTwo);
	
	var results = collection.AsQueryable();
	results.Dump();
	
	foreach(var cus in results) {
		cus.Phones.RemoveRange(0,2);
		var updateTask = collection.UpdateOne(cus.Id, cus);
	}
	

	// Read The Values again
	store = new DataStore("c:\\dev\\data.json");
	collection = store.GetCollection<Customer>();
	results = collection.AsQueryable();
	results.Dump();

}

public class Phone
{
	public int Id { get; set; }
	public string Name { get; set; }
	public string Number { get; set; }
}
public class Customer
{
	public int Id { get; set; }
	public string Name { get; set; }
	public List<Phone> Phones { get; set; }
}
```

**Comment by ttu** [comment]
Hi! Update takes dynamic object with only updated fields as a parameter. When you have whole object, `cus` in this case, it is more convenient to use `ReplaceOne` instead of `UpdateOne`. 

I will check that child object identifier 0-case 👍

**Comment by jayonsoftware** [comment]
It's interesting the following code inserts 2 records and then reads them again, but 50% of the time, it will only show 1 record instead of 2. I am using LinqPad... maybe there is some caching?

```
void Main()
{
	var customerOne = new Customer
	{
		Name = "Jay1",
		Phones = new List<Phone> { new Phone {Id=0, Name = "CELL", Number = "123" }, new Phone { Id = 1, Name = "LAND", Number = "456" } },
	};

	var customerTwo = new Customer
	{
		Name = "Jay2",
		Phones = new List<Phone> { new Phone { Id=0, Name = "CELL", Number = "123" }, new Phone { Id = 1, Name = "LAND", Number = "456" } },
	};

	var store = new DataStore("c:\\dev\\data.json");
	var collection = store.GetCollection<Customer>();
	var done = collection.DeleteMany(x => x.Name != "");

	collection.InsertOneAsync(customerOne);
	collection.InsertOneAsync(customerTwo);

	var results = collection.AsQueryable();
	results.Dump();


	// Read The Values again
	store = new DataStore("c:\\dev\\data.json");
	var collectionNew = store.GetCollection<Customer>();

	var resultsNew = collectionNew.AsQueryable();
	resultsNew.Dump();

}

public class Phone
{
	public int Id { get; set; }
	public string Name { get; set; }
	public string Number { get; set; }
}
public class Customer
{
	public int Id { get; set; }
	public string Name { get; set; }
	public List<Phone> Phones { get; set; }
}
```

**Comment by jayonsoftware** [comment]
Found the issue, 

	collection.InsertOne(customerOne);
	collection.InsertOne(customerTwo);

Fixed it.

**Comment by ttu** [comment]
Hi! I forgot to update this issue earlier, but updating the IDs of child objects is beyond the scope of the datastore's functionality. Adding this feature would introduce unnecessary complexity and degrade performance.
